# name: Test (errors.soulpatch)

# on:
#   push:
#    branches:
#     - master

# jobs:
#   test:
#     name: test
#     runs-on: ${{matrix.os}}
#     strategy:
#       matrix:
#         os: [windows-latest, macos-11]

#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v2
#         with:
#           submodules: recursive

#       - name: Get SOUL compiler
#         run:
#         shell: bash

#       - name: Build
#         run: ./soul errors tests/errors.soulpatch | echo
#         shell: bash
